#!/bin/bash

/usr/bin/id

export HOME=/var/www

function pull {
  pushd $1 >/dev/null
  echo "Updating $1"
  git pull
  git clean -dxf
  popd >/dev/null
}

pull /var/www/einstein/www
pull /var/www/einstein/seminars
pull /var/www/einstein/testsuite_results

pushd /var/www/einstein >/dev/null
if [ -e HTML.tar.gz.old ] ; then
  zflag="-z HTML.tar.gz.old"
fi
# this used to pull from Jenkins but with Jenkins down it was changed to pull a
# static copy
if curl $zflag -sSkLRO https://github.com/einsteintoolkit/tests/archive/refs/tags/HTML.tar.gz ; then
  # even with -z I still need this check to avoid untarring files
  if [ HTML.tar.gz -nt HTML.tar.gz.old ] ; then
    echo "Updating HTML documentation"
      if tar xzf HTML.tar.gz ; then
        chmod o+rX -R einsteintoolkit-HTML
        rm -rf documentation
        mv einsteintoolkit-HTML documentation
      fi
      mv HTML.tar.gz HTML.tar.gz.old
  fi
fi
popd >/dev/null
